const MODULE = "[HOME]";
export const INIT_HOME_LOADED_TEMPS = `${MODULE}INIT_HOME_LOADED_TEMPS`;
export const INIT_HOME_LOADED_MURDERS = `${MODULE}INIT_HOME_LOADED_MURDERS`;
export const INIT_HOME_LOADED_CHARACTERS = `${MODULE}INIT_HOME_LOADED_CHARACTERS`;
